apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:Hb4G+uQQ6UGrnglAihklE9Q6EZLkDY2KQhbw3MNfXCrbQTUCHcmShPtGaa4=,iv:HAbcYj1/OIbJwDUmyi9jsKD5iLtg2xUs0KgR6qr7sBk=,tag:X2GKt919k4Sdt2tR7+6Z7w==,type:str]
  pg-password: ENC[AES256_GCM,data:EiU9x20FAgcipPQ8rg9I1F95BmkOL6rP503CaLOTfPOW0xxuL9a/BSpoLCs=,iv:DWzZBRdOQS9kHD/6Fa2u2FFluPi7t4vpLdmA5eR6AS4=,tag:d/hwkgH0tw7uWrNoeaSR2g==,type:str]
  n8n-encryption-key: ENC[AES256_GCM,data:Ku0mKcx3XqeV3qpljNFhH32WUU0xzG5kjNFs30pj5ZOmPiZLNTvOUgtELocUOcU+T2Sw+5AJFzP7xdzB0ePZYQ==,iv:KAhqupteGnJnN7kBwI6VvUDutDSh6FSx6u4preq65Gw=,tag:2kPyh7DJvdbQlZrHKeTgew==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdkRxNGtEcTNtdkRHd1Q5
        NC80VU05WHZlV3lYRE5Lc2N4VXBqYitSNHc4CkJBQ1FobWRBVjVLSXN0SDFzMERy
        dkZTd2JOQ3JCektua3NETHZDcEJBR1EKLS0tIHdJb250NWFPMlVES2lvcFhCcTN3
        ME1HOEFmSjB5NW02SnNyb1gvbVI3L3MKraBUJ8MLv6hsyQ/HcobP6wgGZjOraaKE
        3jzogY0eWUvHrHVmM5QFXTIcyk6e8MmxQAp9g5DrZDg5XI4ALQtR2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T02:27:16Z"
  mac: ENC[AES256_GCM,data:ieHBod9TenP4J/Ws+iATpEwGYSJ7KBtNgLL15GIsjGTJ1bxHiR/IZe6yCv1kyDo1wc+RIh7gG+sj5vAMq08dRLwu/+k5ORnQMLQVO6HKBvrsf4SARp1zmWL9ByuZO4I1kIi/l8WPQa7/nHeudqaceERgB3y57/O1Ry+QyN0iFtg=,iv:rau8phRhpXYJz1ErgybZ0WBkL6y9DSWtddZqmSbFtMo=,tag:6narDc11qjKCNFYvDDdg9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
