apiVersion: v1
kind: Secret
metadata:
  name: atuin-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:kEp+wtO+ukLkXMsKYZ4zkgEgLHKZOMO40KGbP9Yh2x08YdWp1jcB+7pLvg==,iv:ZvWzDsw+0z1+QM5hn/j3DjLoUAAVys7VMvsFwFzda7U=,tag:dbS94PAvtqtC8d23uwIZSA==,type:str]
  pg-password: ENC[AES256_GCM,data:Gkd6nZ1Cx58Cw9X9OVisf9wW7OEfuAb65juEFI9LorPSA3PKgAhw3qkhpA==,iv:w6hDoHW9ytguVYGoULbzwI9dtV32ZdJY0qrPCDk3J+k=,tag:peNigjCigRTYoCbctWh7cA==,type:str]
  db-uri: ENC[AES256_GCM,data:yGYwHsVmwJbk4+Mj/UPKDx1PVJjiDM/U64tjQqEl1SWbWQ2+RzqHAgbj/GRYZ7N2VbaRqVClRdBWWmtGH9oivV+9a+GP8O7EETnHidef4Cv+pyXEU+H4lckFQy1QPTFmBwY2ewyRz3SSqg6Q0lm2WMBrp3GB1PS6,iv:gk9ZBH4Sa0aJu5Porzggr/1PmSrxyFpopE6pbzHPONk=,tag:l9GzK7L3w732v5wW64i//A==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM0UvRUJEWEIvNjhwS2VO
        dlNJc0Q4OUk4YjFDOFlOVjh0MW1kejlJVkFRClN3eUVCUjQrbHNNLzNueTlBQUFV
        UkpMdkZlekNPSkxxVGFXQnE4R3lHQTAKLS0tIGpGVjhCNFVxMkNuKytQWE5PWkR6
        MklwSzFqOVlLc1hycExNN2VZUFRWVDAKrHdsnLD2cKO0d/e7WKQObzolXe24Xmuq
        2O8JKZu8CeEIqj3s1XJK9htcOJWZMv0faEBaWSgVPXhVyy7xZ4qxDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T18:43:37Z"
  mac: ENC[AES256_GCM,data:PYsF/5HWSb6DnM04b6eiTOXBHhlWhCa9t1X/7F+eZona17VchRocRt/y5CQtW/zhDnM0sQgHD3n9Ap5o2I3NLC03xR/FfrR8BfdrnbOMSYBM1aHQokhNzvhhO1Hj0jHOsb7M4J3QVZVNRwmOt2auZB6SCDHcMnGZ4SMnqFx/wkY=,iv:7rT2JZfhnGHv84FRr1pMeDWuHowY/nz5c24/zerUL+4=,tag:sWlpBGC8LQzArdf8fvqdYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
