---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - ocirepository.yaml
  - configmap-main.yaml
  - helmrelease-postgresql.yaml
  - helmrelease-neo4j.yaml
  - helmrelease-ollama.yaml
  - helmrelease-mem0.yaml
  - service-omlx-egress.yaml
  - service-tailscale-ingress.yaml
  - httproute.yaml
