---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harvester-csi-driver
spec:
  chart:
    spec:
      chart: harvester-csi-driver
      version: 0.1.28
      sourceRef:
        kind: HelmRepository
        name: harvester-charts
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: storage.k8s.io
              version: v1
              kind: StorageClass
              name: harvester
            patch: |
              - op: replace
                path: /volumeBindingMode
                value: WaitForFirstConsumer
  values:
    cloudConfig:
      secretName: harvester-cloud-config
    kubeletRootDir: /var/lib/kubelet
