---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tigerfs
  namespace: ai
spec:
  interval: 10m
  path: ./kubernetes/apps/ai/tigerfs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
