apiVersion: v1
kind: Secret
metadata:
  name: mem0-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:01XfqWulOS1ad2V5jFzS7ELpyszEgR2xIBtLgUD1to0=,iv:pwWoDZE4SVBGF5FDvLStzDF9CBYzM5B/dJSiCwUJQlU=,tag:x3MoczJ0ClUuanhnTRBVOQ==,type:str]
  pg-password: ENC[AES256_GCM,data:RIrG+8hLG85fqwqVOwiUaHsNvHIIxCNmPwyVM5GvcJU=,iv:1dGPWhRcigi0cXubzBG/MFtHS5oIxSFFSFDc8s3Mil0=,tag:OwlYdVo0HlswwaEhaBfZiA==,type:str]
  neo4j-password: ENC[AES256_GCM,data:s+4Xd3gimb407ESU1NwcFW0FXoQnm8bKqDCMZIlWJA==,iv:pemZyfRkltVgmknp2KgJPdonbnxN81jVLNCBTqvSqAk=,tag:itb3Nwz3oMGdlAIm4KGkaw==,type:str]
  neo4j-auth: ENC[AES256_GCM,data:kAxKqZGBmO95FtZKmEFWSxxYQyxxGDJKl8e2wGGgOiX1pVJYGg==,iv:faGe+s8NfacAlUD94L5ZapPrqcAkaxr6Wn1t8sbdsxY=,tag:iiWtTMPQsQ+5KfqmVgreqw==,type:str]
  omlx-api-key: ENC[AES256_GCM,data:TtkKUN9YoIklv/2iSsj3,iv:eRcmgF/aEhtLtYdtZl7Qu16riohsGyddEpNOdmDZRQ8=,tag:TyrI85WsHMva8o/jBjv+Fw==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeFFnb0tOTkF3dUp0RVlC
        TktXLzA5OVl5S002TkdnaFI1SkVnTGlqakZ3CkZkRnNyK1NxUlV6N01nQ211MVhC
        eXhoZ25tQ2xPWExDTDBZYi9BTHlKMVEKLS0tIDZLTjQ5L21tdEJwMHJKdjl2TkE4
        WVg4M0kxT004ODh1SEZiRGFjUUxUSW8Kx+vMKABTTwVxmYhktsTV6RkI4pmMt8gn
        wMdL3R1d8HPfmltBaC43npkla2X9ZpXxxngXtFd5S2T11XJqeZVpDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T14:51:16Z"
  mac: ENC[AES256_GCM,data:7BIBZYaZxbqn4r36PYOCsF4T7i0+nFpBhm9qCC9Tpf3eMzWI1J1ubpoARHhMzWt3cFfTT053P8pC1k779MpPeB3FyuvhQQIlzgV5oP16b7RWtxlPYH6Yo27VdSXv8QWIZN1MnTBTP3geIqiMQlgWgVhVE3D4eZZV0k9iySb6kHc=,iv:rz0xwPvLTdWCwRDMU5x60StcSb/g2YC6dUszRtDVUPg=,tag:iJio0HlBWtM8WddFfhOCsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
