apiVersion: v1
kind: Secret
metadata:
  name: coder-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:fXKY1TC7MuyARlKLhVEwezuCvg3XvW3VejVa/VFqyP0ZVr/2p8LAaG3Uxg==,iv:SyJWxfo/vMj8RorR+/OViSZN9QFeLmiQIL4O+3FSeg0=,tag:n147F1RppLj14ectQ6wZTA==,type:str]
  pg-password: ENC[AES256_GCM,data:sfy/BUBt0xHOvwJzZrfOEZ5f/xs74T/A6PJswYya4HI06BilXBemlzvHOw==,iv:V/Xl9FtJK15MvJBYaPppzTupBm5rez/wIHukvqju2ok=,tag:0+6YJ8nN+bd2ryGdRG4rig==,type:str]
  pg-connection-url: ENC[AES256_GCM,data:lmCWSkm2N59FR298GPfrpes9GpQl9hGVKp8hvhvzns0LLe+1DpNGDZ3pts1WklX1V+hC3PuIvpl+lhMDeKsMLbNEoGcJ0iQnqgYJNUBDcp9Be/vvv5NWwt/lFESXp8US+S51,iv:26iiOjM/kEyDpqOVgRTjxMTFHN23qRqpwavkN+aUha4=,tag:P/TCD3YiF+ZZPmQlGsoJmg==,type:str]
  oidc-client-id: ENC[AES256_GCM,data:QuSKU48Ir1ZSvbLprL1fVOYu4Istft2lcPzFN3R5myoNs88kR7PoQA==,iv:6YqkrsKYiK1RJ4hygE172AI9CGiWICbKYO/NzoseKYY=,tag:XD1iy2ci2vOpe81bABF0Wg==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:J7Uex11IwcUrzJG/Bg0evj7v8fPk3dYEIjmB/utqcfmoaa5X41uMFJgqgARwQJmTNsBLq90D1ryn7zfBzO8W/YwXzdoBPHzN0iuEQ5bgosvwrNqS5RMvuVAzc8/CvdcQba6Ev/ZhSHaCJ2k7+Wh644dVx8UXd3tC9XLB2n/QhjM=,iv:qe21rqjHZoKuTA7p4JJKhEGad1UBX/XtojV41/5r6Go=,tag:TGylrWGVYAWdgnyUfUowvg==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMmw5S2dXR2lPWFcwN0JE
        b1I2WkcxK05qZzBGNFd4eW5NZklGWWJ6VVZ3Ck0wR05pcEhOSEJ4T1poKzE5Q2Fy
        ODFjSERZTUdDNktFVHNiSFp0Z1FzYjAKLS0tIHRkZEJUNmFJeEg5MGhkbkZkbmFu
        R0hVcWFuOW1GWDR0di8ydCtSRlBjQnMKmo6MY4nPRHwBtYjS4NfbCY3HGvezcrA2
        qeIWDpbbRkzdC87iLBxgjpJt+gKGpVJ/bbE+3K4m53wCALffn52W/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T16:48:34Z"
  mac: ENC[AES256_GCM,data:9PgCyHA808Ouxkgm832TXU4CzkAmO3IAqx2Tk/uph+rYHoxxlKIfcBbAZHRdRSkJyBN7NMyXiXVIt2ZpEA7deBZn+6ldDTF24OfEI1JhjGxRthEhoFFyH3kHN39MjTKtJnFXnre9XrjAi8AkPvKKJjRqNVKiNmHC4SFtDzH3Szs=,iv:JISed8oFYwvIGzD37RmFz8UHuHlySO9zu6CxUM8iz5o=,tag:uKgIHCXYEWGS4rLdD9TDNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
