apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:w0d+eQSEyrnvC4W1nZiY2QLzT5CdqRI05CnK8bKdpCYoRi+Ul3ZwDw==,iv:vmkDG/Nhf1isL8S0h7OalcLwOEXGW9MGo5amUUXIRfk=,tag:ee3XKaI1Te65vRcI6TQkug==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZzFuYTRMZXd5MWhSNXNE
        bzdqeG1HcWNFMkEvZnFyZjVtTVBBWE1BaDJFCkl6RHQraHg3SDAyTjd5cnAzZUs1
        S05xNWQ2YmJQZXU2cExhZmhtZmJjYmMKLS0tIGQrcmhsdlptcy9tblpYZVhEaFNS
        UGpOM0VKOGhpZGY0OE9QbldpMHluMGcKlVb6QdBllfM9oW671kfEEC8ozFArIY/x
        EpgHnj9ADxHmALBEQItVLkvTv0I0GUfE7/gSuCdtyx0CPu2J/RgcMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:45:48Z"
  mac: ENC[AES256_GCM,data:8fsYySH/hathmjUWkUacEcfqYYpq5VUUvyPfGjkh84i6dnvsTwXCp/aELO0HKpwGphlSc3dQAvulNFkXwaoQmXEmzP9z1Diipb43Zds7Vwzeu1xHgz9fJYGzpcEZFaYXHf92FrE4CrA6Qw0qhENAxkSXI4G6fV26Z0Es4Bjj9fI=,iv:DRpXDl3KHzJgVi/rxuPuBSzCaTyGfnxfC4OswzbAAY4=,tag:3BC3ihfx098YNiIXiBunSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
