apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  pg-password: ENC[AES256_GCM,data:vawVbUtv649k22PTjt5ttGIJVC8iixwY9hWknjlXAJxllif492ONWw/vXc8vKIKM,iv:upiJHyRq4VbkPFVrAWEW/kNfd/hWhPXfikPDyZ7kX9c=,tag:7i9NrjilPVYlpUJN21jAyA==,type:str]
  secret-key: ENC[AES256_GCM,data:FrzZ4TWB9qovATVhtWJ6azPSXBjUJUmi6u37SlCOkiiGpNK5P9c1XZ10BDOOHb1sP0VC5hd3hr/PfvOvBMYGncwK2rWURg+wGuN9Bs/v8io=,iv:JqCGmCVquQBhT73TowwN+d43yqsrElZD0L3mrLUaz8U=,tag:MHhVXAi0sIlAa2hLbXIePg==,type:str]
  smtp-password: ENC[AES256_GCM,data:WitlGT4vA+/AZt/ZhBvKOf1fzDrv6t3SeMArUUZmnFGebkCC,iv:6cN2DjqYVOf0KM/W5V8FgZkzosHihMKuElJFGhrHWsk=,tag:1QJuj95/Z8jwLUeX58jXqQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dkd0SUVqSkhLRG4zY3l6
        RWxUNVR2Uklsd3NwbGJnRjFzdFRiYWNEYzB3CjZxR2gwODB5enBvMzl3YU5MQlV5
        emNhR1lVaGRsVDE0Rm9oNG50Q2dlRDQKLS0tIG9tekdaTjhsMFJJbk80TGZBSFJF
        MHRQZ25KcWFkclROYzlKcWIyUDNTeG8K2knDrN52h4aKWWUU7Rr+NQEY5k2eB9QF
        1nqBgTDPEki2PZ5+oAp2wluzlJUI49wKZdtkzNVY4UUxsl4lbSMx9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T13:44:45Z"
  mac: ENC[AES256_GCM,data:6uGiibQj0L3m+FhhXCEObgntdaKuODPq2bVsTjppGZ6glP3dehi0GeDHRVlBLdRyEr4b3fRPZInY1ppXC/Fb8fq4rSHAhbYbvotrkwtJ2ErxliKTNJPZjhXct2FKItxVl80FG/lwRRGhEa93wR1bsPxh7TzBrZHsGzDraMQDg78=,iv:tWskacXz8vercPYLEt/kSP84yXb97MwVcFFQL2rLPBE=,tag:56FdDGk+15yj/Q2gGXjbyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
