apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SqNpSIobJhSa96Q=,iv:/+B0GfMjP5aqQlZmb4ISmt1J7iDdpYeqHrh9fodqXxE=,tag:xg1ZqHJTBqQz60JO7cDptw==,type:str]
  SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:vJnX9L3YKjI3ZQ4LXIDdLSG2Zel44xWc/FE=,iv:lyjRk9b4gJuQMVtZ6iyCxM7J2qZSU1QQ3wla357QsTA=,tag:pfQRRhv1J+o3mWbGcB2Y8Q==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVhjc3YvczFEMytjdk9U
        d2pQc1RRandpY095cUNVT05QVUhFOUFzN0dJCmpYQmNGRHRyby8xSGwxT2tUWnRM
        T2I4MzFKMHY3eXFDeiszK2trRHpyN0UKLS0tIGwvQ1dsUEt1YnlheE13YVd0MHYr
        OTBGUDNCUDJxWFpoY1JXdE9rL2tsdkUKCWpIUjIBxf+qgJ8Pvz3H/m5A279vW4Uq
        jrtb4lpysi5ins1SfvUJVjG3oH0rDst3H7PBb7csW/s4hYK+SJvKEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T11:52:25Z"
  mac: ENC[AES256_GCM,data:+xIKD/JRNKWlqY5elxtVS4ROtsdneOBv/VB9MjtqIekb8tyl/GgnnVjlke2HZKFs7JfYA3zJdd1Rlnbzyv8Oetyeno8EtKZUQqH5a5X61rTm2G2hfLK/hziCFnqIrAM4jwnCikeoSOh81A/5ZkzIrt6ppfVzxg5TG+Nh/uvokHI=,iv:/Qxz28tH11IBHY3Vk21ygiaze0Ka+y0bpMT7xuKS//U=,tag:V9k/4sC+nWGxSKv6/ZKmNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
