apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SqNpSIobJhSa96Q=,iv:/+B0GfMjP5aqQlZmb4ISmt1J7iDdpYeqHrh9fodqXxE=,tag:xg1ZqHJTBqQz60JO7cDptw==,type:str]
  SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:vJnX9L3YKjI3ZQ4LXIDdLSG2Zel44xWc/FE=,iv:lyjRk9b4gJuQMVtZ6iyCxM7J2qZSU1QQ3wla357QsTA=,tag:pfQRRhv1J+o3mWbGcB2Y8Q==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:CXlek5EEXywriclcgOGKbA0=,iv:/uoN0KLbA2cJujopIaQQqq9lC5+XgQlvYlB6uxdvc0s=,tag:FMGSLhj8zbohiJCkfVXhAQ==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qJYtLw+uLrVHHcdx87poDoIazGkcjgDiCUn+IOf9TVl4MZom1zChvRPzF+fCar9SOl0laVAA1P04JOOSixPK,iv:ZEXReCzXeuMRz8e+pEvMFQzy+bhxv6p1xc35pWPq44U=,tag:jkIQrxXaOk/chz8toB3MNw==,type:str]
  eliza.OPENAI_API_KEY: ENC[AES256_GCM,data:ySDYZKlnXaYSNvTgDugg,iv:m8T4kWK63GA/dMfv6JFAOErexH8rTtubTDS7P9ZGaUQ=,tag:TpNrIPtaMB0ET4I9fZMQ/g==,type:str]
  eliza.MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:O8tcdbpCzD2OlSfMteYQvlJeRf5MRCobh2/wr4X+nQaPdoO87k8Zwwq1ZvOUm/dxAs2cosbPCm0OuA==,iv:y4Fqjo5fC9N1337N9D0S6Ga6khvHbO+EqeLi83vCjC8=,tag:TAKQiQzjRTQaf+18VOiA5A==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVhjc3YvczFEMytjdk9U
        d2pQc1RRandpY095cUNVT05QVUhFOUFzN0dJCmpYQmNGRHRyby8xSGwxT2tUWnRM
        T2I4MzFKMHY3eXFDeiszK2trRHpyN0UKLS0tIGwvQ1dsUEt1YnlheE13YVd0MHYr
        OTBGUDNCUDJxWFpoY1JXdE9rL2tsdkUKCWpIUjIBxf+qgJ8Pvz3H/m5A279vW4Uq
        jrtb4lpysi5ins1SfvUJVjG3oH0rDst3H7PBb7csW/s4hYK+SJvKEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T15:21:42Z"
  mac: ENC[AES256_GCM,data:AO9TaCOfujwmAVFoy60fN/3ZWZzHrDtVy7tGHqN0ZpaiPn1ewBUDmZA4oDLJ/fXVOSjRIrJRIixXG0hAWg5wat+6CpL0g0QekK66dmvYMX/dloQvc70FNF1L1wF1lQtJ8uJqqpcOVCp8AstaL7MZoqA7kRRy1DcYSIrc327vbC0=,iv:6XZLrmdThl2vAGCWIKtBCQjUwVcVjV8EX+ZxDGqly8Q=,tag:S1DrkGNmzqfkVR+vkAaYPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
