apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SqNpSIobJhSa96Q=,iv:/+B0GfMjP5aqQlZmb4ISmt1J7iDdpYeqHrh9fodqXxE=,tag:xg1ZqHJTBqQz60JO7cDptw==,type:str]
  SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:vJnX9L3YKjI3ZQ4LXIDdLSG2Zel44xWc/FE=,iv:lyjRk9b4gJuQMVtZ6iyCxM7J2qZSU1QQ3wla357QsTA=,tag:pfQRRhv1J+o3mWbGcB2Y8Q==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:CXlek5EEXywriclcgOGKbA0=,iv:/uoN0KLbA2cJujopIaQQqq9lC5+XgQlvYlB6uxdvc0s=,tag:FMGSLhj8zbohiJCkfVXhAQ==,type:str]
  SECRET_TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qJYtLw+uLrVHHcdx87poDoIazGkcjgDiCUn+IOf9TVl4MZom1zChvRPzF+fCar9SOl0laVAA1P04JOOSixPK,iv:ZEXReCzXeuMRz8e+pEvMFQzy+bhxv6p1xc35pWPq44U=,tag:jkIQrxXaOk/chz8toB3MNw==,type:str]
  eliza.OPENAI_API_KEY: ENC[AES256_GCM,data:ySDYZKlnXaYSNvTgDugg,iv:m8T4kWK63GA/dMfv6JFAOErexH8rTtubTDS7P9ZGaUQ=,tag:TpNrIPtaMB0ET4I9fZMQ/g==,type:str]
  eliza.MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:lWeJTz5rizpv5NlLfkxu9T28LwQWUqwzYSMuVx9E6UxUqsA7zIGYqIHVi+kU+bH+57huJdK9,iv:ULX9iUH4EcDh7nF4ty4VDfkIx4D9vVrea+4rgQcsQq4=,tag:4/AFFYexah84BwhWwp2wxg==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VVhjc3YvczFEMytjdk9U
        d2pQc1RRandpY095cUNVT05QVUhFOUFzN0dJCmpYQmNGRHRyby8xSGwxT2tUWnRM
        T2I4MzFKMHY3eXFDeiszK2trRHpyN0UKLS0tIGwvQ1dsUEt1YnlheE13YVd0MHYr
        OTBGUDNCUDJxWFpoY1JXdE9rL2tsdkUKCWpIUjIBxf+qgJ8Pvz3H/m5A279vW4Uq
        jrtb4lpysi5ins1SfvUJVjG3oH0rDst3H7PBb7csW/s4hYK+SJvKEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T15:27:42Z"
  mac: ENC[AES256_GCM,data:/ZvClWOke+xwkX7m0mlxvurJ2Io0wltzGLwopb5oj9qEGxlDcoKFITHM8P+4bGx25TSGRPdZOmADpl7oi3o/VOTt089O2Gbn/flVc0SN1hXF4rdZgcIB/wUKslKpP47OvkvITvjfhDJiTOVgarHtecppoipyQJmDvFooHGa5Sh8=,iv:EIcMELvV4HlU1o9lQhoXxqoIixDVqgUS1hrnfquPIXA=,tag:T5r1AYcCgj2lpewE5p4RXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
