apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8BonkPRlnOy39fAwgq0fLlCVDWMW4zK1ZLt7Q5gaLNg=,iv:tN4DtfEe6PSviWbF21kNX1B8FiUNQCzLY0EDr02BBqA=,tag:cyPNl0rdTHQVC1f3Sdke5Q==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWVZweS9sYnVlNkZZbU8v
        VjRGaEtETnFJbklvdkpVRGFTSjBpOTBWQlM0CmZjc2F4MDJQYXNqNXN6MzQyQlVL
        L2J0aitlemo4dWpmUWQ5cTZwREVwSjgKLS0tIG1rN1FtY3ZBWEY3SzRSZXdUVHFa
        N3VKbjFBT1FvYytSN1hhUEt2L0VBTlEKh2MusHPj+bHuEEW3w/jsGBVOgzHI/w7v
        5ne8VIXeroqmCh4aNPja95hqtDXfqqhum5yu1NEExNmi1Jx0OEImNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:45:48Z"
  mac: ENC[AES256_GCM,data:wdmzra9jh3KgAnq9vPWw+1W22FET9dL/0GDYYkotrl212eQAqY/RNWRKAtNOEiuwvp97s5nB9qWyxUo9TRT4nlsqJDmZNej4ycszuMrpTma3E/EpcM6Kk2tHeE1yjlcQecaZ891230jvfyA6fzTY2LoE/0HF4MoVAmRxOixzTcM=,iv:jbYSJhM8SPNPBhVgA9rKcrh5H1ZM9YtH3VgROqwtiK8=,tag:i6HDVbSos1bDBw1Omi9bBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
