---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: attic-postgresql
spec:
  chart:
    spec:
      chart: postgresql
      version: "16.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: development
  interval: 1h
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      digest: sha256:7a695433df7728a4efa0c66310f4e9e71a37f3fbbc1bb179b8308896dff40a6c
    auth:
      username: attic
      database: attic
      existingSecret: attic-secret
      secretKeys:
        adminPasswordKey: pg-superuser-password
        userPasswordKey: pg-password
    primary:
      persistence:
        enabled: true
        storageClass: harvester
        size: 5Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
