apiVersion: v1
kind: Secret
metadata:
  name: attic-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:uYJ5RblhVwpuB3w2gbMdKIWqlXX0uDVTy9OMl0/bsVA=,iv:JKCrpAXLF4OdInZRxdEN9WiDoYo46r26exXobyTu+es=,tag:ru2Ba1eCEPXbpLPvfh4IuA==,type:str]
  pg-password: ENC[AES256_GCM,data:NBqkBD1/NOkEoofaxRG1r8lku3UaqIYut5OVaGPYHsw=,iv:hObcALbdhcOjDDJcnVm95H2D8VKY9dpgveCCl5+o164=,tag:SeKDdzSuPB+cHbhcG0TJxA==,type:str]
  server.toml: ENC[AES256_GCM,data:0YIOlVqHm7+eLkttFw6OYbGTRfgpiHDCRMvtsj084TNESajuDwvn1RjKufA2MnS9bg2MzG4lprj8P7UcIUZKaJxtWKv6mm39Glqd3Qup+xGsXEkfuEXLrCfG/Ffi0cqe49osoBYwVcX57Ue9ZKeGpaSZcJNxeJmGeJ2vGPyDRm4Ylfpruyzs01DiZmJ7kjCWWJiEnpgpVKFfcSTJvJfFJX6JflyjsgHpgtIH603D8Br9QlEiDX4uBP94cDqiVGwxjdDn1NLZvprJA4ehID6xsHFoyQY8jtz0v6oT9+2dCqCsEIh4RpdDgAZ/sRmSk92T0Mx25QER4aA7s7QKmH/hD1SASOMCm55igUqZZs9ETUIsZdVE7lTTdt7+wNAYmD5nCtk8JmJ85dXf/La1Z4TTDPrLRgkVMw0FV6L9MfvK54NI2dmxhlkrmK9FVt+BFuTF6SgyXcPoERQYLnFy6tkOcQ==,iv:Y+F9SFzqxr96/ntM6cvs0yxf8wYhLB/s4Nawll7VODE=,tag:mG5qqtEIowcdMyA+7nflZQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaTQvdVQ3WEJKYi8yQ0ly
        WE43aWxmeWNZMUQ5N25GaDlzY0dDNmhWTWc4CjNaNGdyOTVyNjJvKzV1YTNvaHlh
        OWY5ay9tQ2VyNmV1ZXkyZWFMNCtlaEkKLS0tIDIrblk0dWtnSThpSzRjTTlVbFZV
        bHVjSEM0NXorSE1RS1VnVFZoZDM2Z1kKjVDvlW7T38iaNc5FoQUpKfxw/M0crfoT
        CgrtwkbyV4a36EQ2nR2iU+TFOYpW70ca9TnWyVeWIsnYxRI4UxEd6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T12:43:48Z"
  mac: ENC[AES256_GCM,data:uW0iJ69A1029oLV35S4AypZ7BQAmjgWCx6y3Yz6ap8SCIvfqA0lcbvIUmqOHVuiuYBWgfBlp+yPrs/dJh5ULOoK+EUMQHltUvYvUkpA1XXfcVig58tdtvGYKM604AWdv0GLpFzTs37cPckFUtWdKO8s/vlABa36QTA3MD+fxAig=,iv:tolvuBGm1BV4dj7m2jn77UD2yhOdhp+nwdQepezoIdA=,tag:KkR5dLygU/VH2wCEDpkovQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
