apiVersion: v1
kind: Secret
metadata:
  name: attic-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:7RVGOqcJx68qCxE1blN3TSrfwDl910u8OaHLwYYhQo8=,iv:ebK2/HNXBARjZxMVWA078TW+He6bPrCpb2hiLMfkVMY=,tag:wyphEtSj4x3RCKlmovDUcA==,type:str]
  pg-password: ENC[AES256_GCM,data:l8wIOzcXngMTbRpqxSocOjuigpK3671HOneA7gCcSok=,iv:EjJymHAmfyn+FQ9ZIrQFGeP1imI5m+pnu5KPHv51NRk=,tag:De4YY2Ok3pVkT87cp477jQ==,type:str]
  server.toml: ENC[AES256_GCM,data:scc6jm9u1yY5HCA2DmmXrZP72nyU2H4+zkZWOC0fhxAvxytj46UCdJ7f7LmgtcJMD5rZT4BC+DvkiP8Y+rywsng8QFMUowYQewSJ8N6flVFvSi9d4v37WMD3vR7EQRz+phw5iOpm8CKbYHnYg3HLVz0bC/xgnZpFRHa7ZlyUC6UpMChLGYOF1l77y/LqHuwMY63f48J/QnAerKutsMcKjUejhNFflCV+lbV2qSSrzytEMnJPMGdVLnLQsFywezrADgiKY1Hrhq8smsU+arMM0Njd2tjSurl91WqpvpMS5Wq/oDaYi0cFJD+d9xT7i4BUzm2SM/CHb8FFYpES8s5ehWFOXBL+J0bQ3v+pvf9xXIi5NiwLpI9X4HtOG59jUmg82hxBjlkMC35HsltVM8anKkUVNHTwr+yHGF6hEZl9rUa8MXbW1B3f/ijDw6wyngnuKRGMOdLmyR1kCOHSKwOHym9RXQ1CWU02,iv:TI88kgUamYMFTOgvG3rWaF3RV9xHh+CF6IaclJtAYJU=,tag:LzP2uX8UuW2l0/Zx+s9hRA==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTXYrbE93VVBETFgyTEV6
        aGZUVmxFeWp3RWZXNlRpSlViZjR5clprVkNBCjdaNUQxR21kQ0FWd2hLRmIvT1RF
        UUY5amdLK0dYdlIrV3RFQTFOZEloNDQKLS0tIHpHYUJyeGhWNnUwQ3pkd0lHb1Va
        dStuN2NJZjlyNW5IRHQ3UDh6MDdSL0kKxQ00xHU9nDW6vxzGbb1WlaLut/K6WPGl
        xQtwl11ZZaAvmIhbYiR8n/JAHU0swpU7AGuQthMbPz8oGY2/wZtsWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T12:53:17Z"
  mac: ENC[AES256_GCM,data:yQh+ug8mlpBAsjCY3/V6bPYgcweJqTGqi1KglKqG7b3sWK7zvbeswukRCDatt/wHv2OvDcWfWCg8vHHJ7/tbUncS19XV1/8I3RFyQGlyypdtlPzLJOvRW3t3GXyNlCJDSOYgXvSUTZDyXOUYjACoZRs4+AB8d+3xNy3snx34i+I=,iv:d083Ho8zZy8uIgTLCqTu9yynLDOey9p6MIw6ki20hzM=,tag:tQcaZD5Iesy586dh+25bgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
