apiVersion: v1
kind: Secret
metadata:
  name: attic-secret
stringData:
  pg-superuser-password: ENC[AES256_GCM,data:qwdqQJ+QnxSyosKWK/UMyJZD6Woh5UVbdlZ/m2PfSbs=,iv:a/Ux3dMn7UTb08a4FvGo+bxRM+MKsbTAvEaiXcF4avQ=,tag:SOmpibiIBRpWPMq8XZXNHQ==,type:str]
  pg-password: ENC[AES256_GCM,data:d1cNGpFenorxHcSgXkWw+GwVf2CjwT62wNvlxyhKhd4=,iv:aBByluy8CcBF/paydr2R9g2w7dYj1vIuwNDRWICZFqI=,tag:N0npOCWZP8rugf2tvNtoUg==,type:str]
  server.toml: ENC[AES256_GCM,data:sJD92whhkhieX/y9dFvp826H46tM6lW+acuODekkKL3m48a4YRuYch/I6VZiqAij/qLVI+GD2cI/aF3ZDnGQNI4D9BjDQD/4S48tOz3mrv1kVshtXk56NlEeQW8GmPL/g5lXwLCBHj5J1SDfOtdKU51furHbXWv96ejv3xIP5C6b6wjdlXDYVHb9piBOR0GgG+oZHthZvWxGdH7n3VH8/enZSzVdhXuN1nICDKoiSSZ0OcIwvRpkNi6L4V5Un9UqLPteDFvDLRRToGChCYv3fCxNj7bxe6cjb7PLliMCA8iukZZmxHb5cyZCGWhzFP2AKi1Elni83OgI4zV9RIXTJvo5yHrsUr+QWp+GQJTXP/M/QRDiiOjA9fRlSwxCt8qkOclzlAiEylYdsEsf,iv:sv+nOKKKdOQs97Arc3uGpM7eGPUmYkvuYBG0RAlI5ak=,tag:xmzmYynRSnEVzEfUh/9rXQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdHF1UTArQjg2djdzanZz
        MTV6U0hldDhsWTdsM3FmMmJmMHp6MmkxR0h3CnJTTzk3UE9yOEUyblBhVlRNU2x3
        Y0RVUVY3WDhRNGFxNlZ3azd1M0pPbXcKLS0tIHZKMlNTOElaNm9Gc29mSjlRNytF
        bmNIRHIyUXlHQ2dYdDNIUFVleVE2OXMKYdcLVwAI24vhNdXN8KnkKCf0/3EjmJ4U
        c+c+b4BM7wt7EeCfcLvw7ZAPZRXQoBQowpkKAAAl0tcJMmBejVcfeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T17:03:37Z"
  mac: ENC[AES256_GCM,data:dsklwz4FObtCy5YBAzDihhFnq49NgAnz7Xr+fHzrqMLfY37q5nVOhxX8NgYLaMEhAJvLqiwQaB9CzLwj4Z1Dy5tGreMW8ZO/+2OnluVflfq8xDfyTwyniP0xA4gPjBazicUK+ex3uLUvSQoQVl0+QkwrhEYdKQ7xJICpFxCMEzM=,iv:Uj3+0dJLMlncFOCdjd0HRcwh+nmz28thvc2pGPBT/sM=,tag:8yxTexu0/Y4k64oDYYnSag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
