---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.16.107.1:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.16.107.1"
  - "talos-01.beaco.works"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "virt-01"
    ipAddress: "172.16.107.201"
    installDiskSelector:
      transport: "virtio"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/7d4c31cbd96db9f90c874990697c523482b2bae27fb4631d5583dcd9c281b1ff
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "3e:25:a2:b8:6d:92"
        dhcp: false
        addresses:
          - "172.16.107.201/24"
        routes:
          - gateway: "172.16.107.254"
            network: 0.0.0.0/0
        mtu: 1450
        vip:
          ip: "172.16.107.1"
  - hostname: "virt-02"
    ipAddress: "172.16.107.202"
    installDiskSelector:
      transport: "virtio"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/7d4c31cbd96db9f90c874990697c523482b2bae27fb4631d5583dcd9c281b1ff
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "3a:91:0b:b4:1d:2e"
        dhcp: false
        addresses:
          - "172.16.107.202/24"
        routes:
          - gateway: "172.16.107.254"
            network: 0.0.0.0/0
        mtu: 1450
        vip:
          ip: "172.16.107.1"
  - hostname: "virt-03"
    ipAddress: "172.16.107.203"
    installDiskSelector:
      transport: "virtio"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/7d4c31cbd96db9f90c874990697c523482b2bae27fb4631d5583dcd9c281b1ff
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "2e:3c:82:5f:f5:b0"
        dhcp: false
        addresses:
          - "172.16.107.203/24"
        routes:
          - gateway: "172.16.107.254"
            network: 0.0.0.0/0
        mtu: 1450
        vip:
          ip: "172.16.107.1"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-registries.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-tailscale.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

