apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
stringData:
  pg-password: ENC[AES256_GCM,data:R2ZrLRkzkUDh4cqtrQeH48RbL0uqlqo5ZmSn0k+mGkw=,iv:pIVhEBF4JuVQ/jwDCj25ZwMzr6MujjTsohp7PW0OGaM=,tag:JBXTTndlrv2cgV1g5P36mQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUnRibk1jajNOVDFmcGhS
        K08zaDB4RjdzQjdQNW5IRFVHbVpTdEVpNkVFCmVwNEI4cUZkb1UyRjFLNUJ6NFZY
        TFgzbkkxRDFjNGNZc2hyTDZFUm9ZRGcKLS0tIGdjKzdLT25uRlFzaXVyRjNONVFD
        MXJJL0FRNHN6Lzg5aEM3OG5FL1BwTjgKYvhyTalB/yaJPD2XKiY9ZN3YFoWpjFE8
        pTW9gR6MV1Iv/wqLI9p/+A/Wl26qERzEoANH2e8hfYQ2Su7GPtr89A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T17:25:16Z"
  mac: ENC[AES256_GCM,data:M9dz/BYGETCFIVxblsfaI+x0g9YiCuP5IDM95DMqZnD9Ictn6fO2jjViEMSPpxgyfrYVGT+vNgGl7TnHzQDcH6BmAIWbuNaPAJUrK+kA68/3GpyZAdoXOFPanSiGiNCxP3ija0q+zDOMkvOPNtsTHfU76WGjjA7jlol6bNQq83c=,iv:Q7VFpNqLML3jIPOiXi8cW12lmHu7B4z9mCKk0AadtB4=,tag:ZKzQCE4TmOHx2TDwMe+Hnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
