apiVersion: v1
kind: Secret
metadata:
  name: zot-secret
stringData:
  htpasswd: ENC[AES256_GCM,data:S/4QFfRgczO347xpDKEi1jttOd9IFEHP75j5G/JRl64k3d8cZZ1zkYOSJWWGnVy+g4oszO8wdEDGv2aZzhwuxUpB,iv:LtjIiQX6PZN97m173fmc7BQG6xhTRv3AJH+BQdSKELc=,tag:7Blnyzy7oAaBAUza+jxGcg==,type:str]
  admin-password: ENC[AES256_GCM,data:nKBMs8+eIKkiycHgDGS12B9iKpzc0hUTLlYHMziB+XU=,iv:cTCYvrqWbtWhRE4fRY0gj9Axor3EwB1A2su6fOmBw/w=,tag:npFsSKHA+jYAaKnO8mrxKQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaWdINVR2cHhFNVhUNzY0
        dWZGZE1xbkJyMUdPbjBRVmloNTVJV2VmZXdzClNUbC92SlBHZEJwbVQ3b0ZDT1Fs
        Qi9SNEZFYm9TSUxNbThSdURLZXJIVzAKLS0tIGtwOVBiTmVxRklUeXZPMVFHOTVx
        TSt1MFJ3SkVpeERnbndaNE1KVEpvYWcKwuyRv0BwrsuAgPKyb/LQ5Jl5ukkFTBLQ
        BnO/i3VxbhOKZw/MqgNnk4d/eOzvigRBSR1O1wSGXyM5l9+gJLyPCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T03:10:35Z"
  mac: ENC[AES256_GCM,data:L9FTt13EHKhKce5WYR35gIhspwisAVc8uMUfNBnV66nTDeeRKAP0Xfwp7WBJKV5Pf4cyQV112h36R2IzsBcy7RxHmpNWNYTv3Vs051wbSLAzZXX5nIKa+wjovm7wUAsDQE9Qxr9Aw7fkDdnD+/fKSBeNKfgwYrq7IcjWu7/uVzI=,iv:rwna2ybIX+Ja1qUvsCHM9XvlXCkZionE9dLY8iXTp5Q=,tag:SvY1hM6yv42NO2kX4iNQmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
