apiVersion: v1
kind: Secret
metadata:
  name: zot-secret
stringData:
  htpasswd: ENC[AES256_GCM,data:DDQVSE1HKbnH4eJZL00krQzzZmyjdxcMOIYITjM+4CVgUDILbRSgqtE8B4pBSLw9ZtFmudMVQB6kmaZ9tv8lb36C,iv:Tw+NR+WQnk3tbp5Ks6Fve8aZkb8/K6uFzH1CV1GoIeI=,tag:mOBQaiEeGU2N0z7YOiNDEA==,type:str]
  admin-password: ENC[AES256_GCM,data:c7LMMqPc7hr1FFGfMLOKiuDwT40R8xkhQcABnXX/vTU=,iv:Pr7120cAOTCm4fbvdvu7ZQgZt1qOZdko35Rdaj4j0OM=,tag:SYbUT1Z1dI3bYCqJpy972g==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR29rcW51ZVlHUC9HQWcw
        RjBsbTU0NEtzVjJNRVZacWFabkRoRFRhRURrCjVwUWQ0cEJhWEhUNEQ1NlN6OEJn
        bXltUXF2ZzlnUUlraDY2VWdhVk5HMEUKLS0tIDRlTVRjaEg4RndPMUw4am9kenE3
        eFJqd09ucWlZb2plbVZyKzd3TmZWekUKv41sculbJ9kPhpltF9uye8Bb0feILrGc
        hLacwi7w4/8KuKRwhiP90V5bS8Qo116aLQzoasoUm2939pPViHSt0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T17:02:51Z"
  mac: ENC[AES256_GCM,data:m6OVdlgL4UFwYsbcSAdujceGZYD//LSMTFt8LM1WQsUoz0X3KoMrLCDHNofuHgATKevItkuo1K+QJn2xMrQ6gqXwi/PflrbQVEOqdzm3yFAmFZiSZ0pRtBPew7qgQHWi7O4b0705RIibVyboYwRNJ289hbtfhM+7S/iaR9n+Mbo=,iv:XvjChKuYyvK8krGygcxoO/dhzgLz05/TybuIdTsbzV8=,tag:zdIZwINpw9I/1WhcNHM95g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
