apiVersion: v1
kind: Secret
metadata:
  name: zot-secret
stringData:
  htpasswd: ENC[AES256_GCM,data:fDJO9m7+zpjH378tnAvxOqQmUQuhFYHnHB3LJUjnPkJchCFvQCD5K3CLqpwZ4n8Il0vSw/mMfdEGMl0LN8CeaMfN,iv:/5WnYrw+qXZfVxRkUInyMQcZxO2ckVu6+/dRqu9xGpw=,tag:tsKfL33gRq0tYOnCsa7Ytg==,type:str]
  admin-password: ENC[AES256_GCM,data:eHZSN4ysSriIHSfVZQ3qsEchS26MjIF45Ayfpzoq7IY=,iv:phBocTaWlmWNw0NT4iS03P24onjezLf8M/XEUmY9Iso=,tag:qkqpDV8Mq0QYqPJCH5MBQA==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeXRKVDFzYlkvOU44NHo5
        K2NmQUUzTjR3Sk53VCtUTjZPVXl2N0xweVVzCmJyNUhHaWN4aDRvN1BsRFRPWkJP
        K1ZuT1B0bjB4aG4yb2habldlOE9jZmsKLS0tIFpKMldiNlN1MFNsY2R0M3d6bmU3
        bmVIajU0RmU2bWF2TEJFRUFuUURwaWsKt+pTMKX9HAyZTS/sabtSX/hlNktsDcvR
        duQSTpwxB6RhIp14Es5eIvxW6kuxJpRrme23DiTB8x5r62lkH/MImA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T06:45:44Z"
  mac: ENC[AES256_GCM,data:KhdPJNIrcFKFFG5CfCOz0PmVhe+1CMeWSICaYwMXtaTDIgoVQk523IPDj6ppc0PRULuN1mBAwpPYitp51rk0vbppJGBpAFFFwTO+OTJRzbuLQDLlthabTxlOU39CD37FXWAgFQZlp3H9IRvagG6XQjyXzdP8AP7ebruYo/On+UI=,iv:7AKKpZz+pO0MrqlIfTPPN0Fecln69TGZysBvmTnYJ5U=,tag:JR+4g8rp2HFn8jBSOGTODQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
