---
apiVersion: v1
kind: Service
metadata:
  name: zot-tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "zot"
spec:
  type: ClusterIP
  selector:
    app: zot
    release: zot
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
