apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hdLQQFSD/abhHu48/L238sEvxdp0IGDYd3e8rvmGj97eIp7k+CSRrO5zfFANMuMH82x9L8eCms2s/gC1U4CR5/6wFDtL/ZpQ1lFYGzSStlSf0U4XolWAiQPWsz6t0sKPbLEIwXnunsdic6lz0qqCXrFpFxXwEWZPuLGWUK5qAns69kix7u1QCr3wCTq8bcAggKiqCe59FXtmrQPNRkGiCdHhY4qdjULealti7jD41Ajj2P37,iv:s3XwVCU6C8SvDZKUK/KSsQi249mx16djDIgZMHU9XUY=,tag:FpiHXWpMslElSwmb5aTL6g==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheUlZbXN4U1REMFVXTFVz
        S1ovNUVxTEZEVHMvdlpLYnZaeUE4WE5xOGhBClVadFYrSEpsV0RlQUZ6eU5IZFp0
        RVZIY3NJWkNYQnF1N25sSWQ0ZWRiOWMKLS0tIDZ6UDVNRW9LciszTndudHNZN1Va
        Znk2WWdhRFVBOEdxMUhkbWM4MGV5cnMKloogBVaXtGWcDm845FQodAbNgimGhvoT
        bOYy2nvVPdvRe0szOEW4rysICUYDZRr2pOVuTwt/Usc8/gqjUpda/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:45:48Z"
  mac: ENC[AES256_GCM,data:5SFYAqwh4dYg6GVh0ZjCid6Iid+zUC7d5GPZzog3trUGUL6N5rrwkTHk6Omee2DdFIXLiGKn4ViP0xYrGDjUbcC+J+4ZiyV7ve+b/ZHBuA+AU6hfY3acoYlOuC2XNZpGKvM0y/JveVautw0JJJDtKvvImjOHTsw1C4rgBPh14hw=,iv:S6EpfX0+M/razta7oIJkiNSK4IEBDPNXRcJ8HwCPV48=,tag:pOyHglQ04Km1ca5VPR3efw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
