---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./mem0/ks.yaml
  - ./eliza/ks.yaml
  - ./zeroclaw/ks.yaml
