apiVersion: v1
kind: Secret
metadata:
  name: talos-image-factory-secret
stringData:
  cache-signing.key: ENC[AES256_GCM,data:hpoMjzk3zqRaHZB/w8P4y2fTYKLIpvh3i2RZWrw6NF+Rs/eRqEdKeqK7voXbiNWFK37Sqp9hg+tNIfqnS/LLec2gIbNdyYPLkJBCdDGJkpONQsgObvK8VxhpOIoxOOdbkNtb/oSWwgysVEAuFhxvskCvWV+CG/GNAlj5RyvMFLX6H82kcM65pvIwqYZd57jcXbQXoLs8P+pNGx4cBwp6D7nCDXZDu8HyXMluRWvdR3+zbZZpSssBl9fhkKA57ADmS08kWig40DzHiVLuKB6UYJL5Ff6vqIIf/iBjxkPOQkK16PU=,iv:O+XBY8Dna9OGb9fkPoMZzSDD84WB4e8bN2U1ZD7Gpys=,tag:1IO1c0T8XXyigdnro3lQow==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:GAJ22Cgx6BpKgTGDZXTeEzwmslqXgqwfMdgaTPu9X34yauXsxIAA1g==,iv:mVWVVplHegiFXpJFl0b0kJ05jE3xXe2SftR1IZ85tC8=,tag:+6DZ+szBlFtdMUrOvnNhrQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MlBBSFl2TkNoYk1FNm5n
        RlFTcUx5VVpHUXJtNVd6V0RDUWpKb1lHN2drCklwTDFneXFZZVRzVXdHQllEMWFx
        WHlzdXkvYjhvL2thcVVJQWlZdUt3RWMKLS0tIGIrbmdOTUJBS21mbE1VWWp2a3po
        cGY0OGhNMngyays5VWtoalRyaUZhWXcKs7wD0rjlpN5MaE8EZlZDMiTFDCzT3lkp
        TXbQqXU4qUbsCbhm3DtgY2vdg0wWVmyhVlzpyV7ioHWI6zDP1dk5ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:52:09Z"
  mac: ENC[AES256_GCM,data:ZricScsF8VyR4IFaW+HbSi8z0L48uSc7Ed8Y/5rj8/Pj7yHS85EUUPaOCrKec0iRpXHZHfOzj2L1hWCKcqUssh777DmXWdgKFI88sR78oDX1nD4VUV2+cKRZRGNeTe4kGBNTVDFFSJgtaoTtnl0api6xiCwKE4suaqxghFAoUUA=,iv:JZwX7J/T+wsp0XF6jd9qXOPZDHZgDxPs2gd5TuUCOG0=,tag:sDReI+zYOMKnVzI4UBB8DA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
