---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager
  interval: 1h
  values:
    crds:
      enabled: true
    replicaCount: 1
    dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    extraEnv:
      - name: HTTP_PROXY
        value: "http://sing-box.network.svc.cluster.local:7890"
      - name: HTTPS_PROXY
        value: "http://sing-box.network.svc.cluster.local:7890"
      - name: NO_PROXY
        value: ".svc,.svc.cluster.local,cluster.local.,cluster.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,127.0.0.1"
