apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RbLmL4HzC8n15W48n9xQonCFGDvqU39/hMDJNC25iRflmj9WT+xrBQ==,iv:/KjFHD0Pp+8vcri3CS8GkvwwOXaPglmgyCGWv4FzUPs=,tag:pGNYloR/9ONqsJ+IWiZIvw==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UWJRNFpjTHkwZWRWZVJH
        TU45MGN1a21hbVFiN3dWYkZIa3JQU0J1N21BCjh3NlhYeGRSQ3R0Y2c2VmpOVHdm
        RkZYQ1c1QWMyWjlhNyttbS85OStEem8KLS0tIEw3RzlkVEdrWXI1UGN3eGE3NjFZ
        SmxxQjBkbzVtY3NWQmVLSm9nSlNIWXMK1Kh+hG7XnG8LYDLSAVNbG2BU3hzKq9jZ
        cSzqv504WwIp33b6wKyLKQyr69NZNztjyla3j6HeXx68p/IaPMz68w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T13:45:48Z"
  mac: ENC[AES256_GCM,data:HDOpR5FplnfhIwUIyxS3QBXFMxpB3BWO/lJtc5ATsuguzJEj6C5pAJLUoM5qCSqwd5SFiX18n9shn56jKIerT6T1g+SUiUWFrkgo4i7BShdwzT9DG/V9TCQaNF5JToz7+1VlNEgTIKx5Ym0kSZQezwZsEfB4ZPYiXFjyFw8Y8cQ=,iv:86pBosGjgLMw1MpEl7Nj7LfnL2JEATvKWJEFQSNSmHE=,tag:dKOEqbmZMHfLWOYA9b55eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
