---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 1h
  values:
    global:
      image:
        pullPolicy: Always
    image:
      registry: registry.beaco.works
      repository: code.forgejo.org/forgejo/runner
      tag: "12.7.1-amd64"
    runner:
      config:
        create: true
        existingInitSecret: "forgejo-runner-secret"
        file:
          runner:
            labels:
              - "ubuntu-latest:docker://node:20.12-bookworm"
              - "nix-builder:docker://nixos/nix:latest"
          container:
            network: host
            envs:
              HTTP_PROXY: "http://sing-box.network.svc:7890"
              HTTPS_PROXY: "http://sing-box.network.svc:7890"
              NO_PROXY: "*.beaco.works,*.svc,*.svc.cluster.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,127.0.0.1"
              GOPROXY: "https://goproxy.cn,https://proxy.golang.org,direct"
    kubectl:
      image:
        registry: registry.beaco.works
        repository: docker.io/alpine/kubectl
        tag: "1.35.2"
    dind:
      image:
        registry: registry.beaco.works
        repository: docker.io/library/docker
        tag: 29.2.1-dind-amd64
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          memory: 2Gi
    securityContext:
      privileged: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: forgejo-runner
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/env/-
                value:
                  name: HTTP_PROXY
                  value: "http://sing-box.network.svc:7890"
              - op: add
                path: /spec/template/spec/containers/1/env/-
                value:
                  name: HTTPS_PROXY
                  value: "http://sing-box.network.svc:7890"
              - op: add
                path: /spec/template/spec/containers/1/env/-
                value:
                  name: NO_PROXY
                  value: "*.beaco.works,*.svc,*.svc.cluster.local,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,127.0.0.1"
