---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: forgejo-runner
spec:
  interval: 1h
  url: oci://codeberg.org/wrenix/helm-charts/forgejo-runner
  ref:
    tag: 0.7.3
