apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  CONFIG_TOKEN: ENC[AES256_GCM,data:tOPd7276C0D032QA07QnY1/w/ZBI7hTo6Ql7DnTfT5IeUc1QYG3ZcX8NEQ==,iv:YhysgTmLFvn6+3lE5vwXBZYm1jHl7VkL/92c7yeZGXI=,tag:DAYDqLxX8ojZKz81F6NUvQ==,type:str]
  CONFIG_INSTANCE: ENC[AES256_GCM,data:bWKeUw5NTLUyRH/9nlwxZ2VAx8GhR4d/hFeAlRye3scSxMLuELXnPQfNFcLyIg8JrHnZFwmT,iv:j0HO0xaRRTu+UvZIghZ32wKBiV/DpAoyOAvIjmKLfVo=,tag:eBRXaxFpquMTnqqsFLS7Ew==,type:str]
  CONFIG_NAME: ENC[AES256_GCM,data:hhWQwEaxaxjV7UHh,iv:uzMj+9EPXjyn/ma3qduBsRjjr1iC9E84EnenHpTjOvY=,tag:tjZPAoTD2bzZ8HOP9H2jPA==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS1FpMmRXcmtZd1JmLzBX
        V3k3UG5zaEV2M0tGWkVNRE1RLzZ2VmlDMVVvCkpPYUoreWRreUlZSHY5NzVvM0Na
        MmYyQXpncUkrK3VMQ0V4RGErN1dUQ0EKLS0tIHVGVmU2VSsxRHRaYUpYTExqWVl0
        c3kyYTlJK0JWQWtKUEJpZUYybGNNb3cK1EnIE20xr4wGs5lB4S9d33l0tSQH4/gn
        WdS1ZTISKO/vwkpx8OAkVO2UCP5PGgvBE8vhXep9hZJS2gqnIom5QQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T00:31:55Z"
  mac: ENC[AES256_GCM,data:qMgxtJeYS3+armwbK120wC6ke/HFDPcxJiI/vLgny5sKiCZO85GFyfZd9FYD2J3ImhN65AdEn31QUHT781e/5yEuw+IQuosNRuF9htFWSHqe1BphorwBhnUoUofq6Fy937GF2hrt3cNWK/Rvp5tyZl9JxmIjBolbVAU0swwJKhc=,iv:QTsLzC6e3Zk1QFwtGiGVvdiq3OTPVHDYuD02S9DiVy8=,tag:e1I8NOUiGVKzs70cnXx6/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
