apiVersion: v1
kind: Secret
metadata:
  name: forgejo-runner-secret
stringData:
  CONFIG_TOKEN: ENC[AES256_GCM,data:Mvi+l9u4QKANljsMyaAMGh9zSfkLxi3X6g9U36S0jAaMK9/lkwmoohLR5g==,iv:7LFvhNORk2jGx9YosxRgyby3Enc7G3hq7Xaa9SWuz/k=,tag:oAQx2+bAMOzwTgKw7MIMZw==,type:str]
  CONFIG_INSTANCE: ENC[AES256_GCM,data:BHcq/+4albD7pqA6R8TnCVyO8CCYzSIN2FUqYQFQ+5n0HXQF9Kof8IwHSfbi3s0NNi8JxQ==,iv:IIFLEZi+URsTKYApRs+b1DZIv5jfR/qdPKSCG2szWr4=,tag:7bdCh3QnczZPdujgAhqhWA==,type:str]
  CONFIG_NAME: ENC[AES256_GCM,data:9A89qeBUpPx++qAT,iv:bJiBQxI15KQUeFeRpghxDf6MmuNwRzi2cpvQP/5V2zQ=,tag:Hf3IbY0FmDesKj3Dt2HY/Q==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ0pERFRRV3VxWDl4Qk4v
        RDB1cHRhV0ZDOGtFUmcxUDlWdSt2SEhLblNVCmJJNlI5c1RhTTFlS2p0YSsvUVJi
        M3Y3VVNhOWJ4eHRERkdsMGtrTjhiT0kKLS0tICtuRVQrQUpDeGt0NjM1Qmp0a0Z3
        WlppbVFZbXVaSUY2dlQ0bnVrZmsyYWcKRrS86uNgHyIpQ9Y+VvnW9goVlEydStT2
        8bhAza9mOBBL8dsEsiILuUXLHC5uet+G1L3Fki1xq8e4UBaz/wGr9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T10:15:04Z"
  mac: ENC[AES256_GCM,data:zDfsRNd0tA3K7BXBxAn0fn7Spq3RxZJHkgC6kxYLt8EILJVTto2A9kmbJB0XbQ4AA2d1vK7UQpjRhUUTYigP+Td+RbyEGTn2a0HgiG0S/5sH42ANlkUsnEc/ufbh5GEx/TQmWR+e4rMFinGIn7usRnnBCn0e9pmxVgF6UNZONnk=,iv:xiC6LvfR2eBEkdtVszcwPCPcyh8VD5Kk4FoQHjc6zzw=,tag:wSyvmgXTEQ0MOjakX7hE+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
