apiVersion: v1
kind: Secret
metadata:
  name: matrix-synapse-redis
stringData:
  redis-password: ""
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cGFFZGViYnFMMUN4bTFK
        UzVMa3NjNE5wU251Y3pwamw1UHlUT0tVOWxNCmh1clFnVVJ3WnptLzFHTFVQc3N0
        N3BhYzUzUEtiOGw4ZzdlbCtIdnlCS3MKLS0tIHRqWm5sMGtFMTdmZzk5MzRxZW1k
        TEs5WE5lUlVFaWtrNytiMGhOM2s4aFEK6a9s3gZtn1ZITe394D1lHOs4l5O6HmHj
        xGmGJt6rpejzjZgpGLr8T/C+9l7tiF30sbJJkUtvtmTI0TpvrVrmfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T01:34:43Z"
  mac: ENC[AES256_GCM,data:Prq9FpwgvJhcX9n4RRFeJNYxu8XPoT+ZaFMmZ17qv9istFAOStx84hEQQzuqw8Xq7HPlxQ6vH0wt6GouEB/fndO/0hQjX0F99bC3AFBDcVqSGficPLUy0ueOMaPmrLOBrOZcHUbWsu23dSKUVnR2f3V4g+ARx2iVgFDGVa1nFls=,iv:BmO/xMBkJqOA7mexCnILUcb+q80CtHb6ZwJ2Hg822qs=,tag:cyopkQpBpyNzvivLdFa/xA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
