apiVersion: v1
kind: Secret
metadata:
  name: matrix-synapse-secret
stringData:
  registrationSharedSecret: ENC[AES256_GCM,data:vPcvqvrgwGf/gmWL39oVqB2fBKtMZ7bSkGX563z1i0r8HOxSX6Z/oCXhw/mStKUuBKMFpflMGM/G0+KHpHf2kw==,iv:C1O2uQ62tX7paDwaU/CsEX8ROqYlz7L4OB5Wup6MehM=,tag:bPp+KgTcuzZMPswQY/S5dA==,type:str]
  postgresPassword: ENC[AES256_GCM,data:hOFT210KSykJP2P8/JJ47YdEgIZ0+ja8CoKpgZBCvEFJM8+S5753/lE12g==,iv:eu0hdQvLuaRauGeOohdt4Hdtjzx103fVZAdRa+0Lcoc=,tag:5MMH06JFcttEGahPe67q1A==,type:str]
  postgres-password: ENC[AES256_GCM,data:F4HLLFVq915hd21h+OddD9WRN8ALQL0e68yxz7nNG+KRm1/CMSssLmD3Qg==,iv:lYKE5Qj2bMNSdGXdQmLEoYuAQTheH66hGeaz178RHhI=,tag:lzs+JWrBdPJ7QPDUZU9D9g==,type:str]
  oidcClientId: ENC[AES256_GCM,data:K0FEbMnTToNxeEWOOPM/K5iAt2d2vdMsY18alnZDxQZUZgvg4SsGVA==,iv:mU8UcXhqWitzipTh1DLiIiCzoU8xk+IExt1aH46e2ho=,tag:AEBYjqG2bPChgYejSthJqw==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:N6xFrZ0D21Ply8WPxSxuSE5sLmX839lwGN7XuAxH2zsgQdPfrpKaAfDfAf4ObWt9yFJkyyV95K7InEYTj91afhUAEXkHxSNi+cwY5DiTgWANo1xLUBc28m6tQ+Arj4T1WSPsoxO98GstQ3jHB9qRdaiVa+lNTAn1xjX5muHlBTs=,iv:ptLmB4a/udoWtWlfJdoDOt28A9KsMnlydXDtykcVgsA=,tag:Gr5T1R3KyfxWXQ8sLeTIGw==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcm9TcHUvdjBTSTdRUnV2
        cm9TYjJGcDhoWGNSd21aaXZEYVNCTE5UZ0FrCi9Rb0l6OUZJZUNnRHJlUStIR1hC
        UHZneVFMcnNpWk84ZWR3YjJHUWhsZ3cKLS0tICszWTNwZEdMNkxwZjVYbHUrTDhk
        OHYvVmdtMDMwVTYzZm1LVmswSHVtVncKEDjuoPCeWyTUVY6VkgYcCD/lCAFCP5sO
        OV4QihERmnrei80JEAn5zeCdsTaklMMt9CKpfzwD149uCwaphH8IVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T01:21:15Z"
  mac: ENC[AES256_GCM,data:s557MGdKfsU3ebmNyqVWkwafJV3RE3Q2555NMa/LTd0QJ67WICeeFB9Y4qAuwJRZbJZdXC8RiX4ySnL6w6YXQw6VApUVbhCJ/pgWzOt52zqE2VQhwIcQTmUWH8A/mrHOXz0C3YFAY6j+j9bCAlzlKeloJhfTBNjE6WEqc9hsjFA=,iv:hI7iZC+ZLyXd3/jwdOQDwkX5F7o5JSQv5lrgTbJ85l0=,tag:bktwuruI4tDz/1WKObFeYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
