apiVersion: v1
kind: Secret
metadata:
  name: matrix-synapse-secret
stringData:
  registrationSharedSecret: ENC[AES256_GCM,data:M0YcGZJ3Xj9/t8EYUd85b/cgozCGmKZS/x1u9Pualsfe32LkyNl4NrPxCU9tCSR7uxwAA7AywDxL36vW3LEROQ==,iv:8lYjv++KRqBW+r51pcH9UP0cnYr+efRJbWtScC/H+T0=,tag:JbGa5q/5HxV9oq6904JPjA==,type:str]
  #ENC[AES256_GCM,data:590y1+J16+ZOt1T34AcfeoFAADzx1GlmeE+xe7/vYMSr6QBiCfeQ8hTmdMXOw0Vq+g==,iv:62WQOrf7/+9Y3C7MyqV2Zc/hpvctqNjzGNZvG0tyWuc=,tag:DZUnbAbNohvCIuCBuLYUuw==,type:comment]
  password: ENC[AES256_GCM,data:JADg1FhI14jCjil+f5Uc/r/d+fgzIgm6Nezp70CMK7OQlJS3qJtUreuXrA==,iv:DJWx7a3lcuK3nICwz9dz6VrOmoJwpBDk6jmh4Qo4rSo=,tag:Yg5jgcwQvjDsbRr+megfqQ==,type:str]
  #ENC[AES256_GCM,data:NaNMoM58UjmWspfwaUYlVm5ZctdyF822LbX7+rhVT7cDsw==,iv:Bc/vjQVokxiSz9GBSNC9S2nPEHVAW5nvEajZWPN/TsM=,tag:xi5iY+eroP6FdUR/2/bMwg==,type:comment]
  postgres-password: ENC[AES256_GCM,data:uVy4B0WIY+PlWa3YUYCog+mnmHKS65Z2ntMibZHi7AFtEbbDHuCVW1lJzA==,iv:112m0hFh3fYbq/tAGT82/SZJmD65Tqtyzu6H9MRT0lQ=,tag:UtTq8lMuAQvr7wEgqqULgg==,type:str]
  #ENC[AES256_GCM,data:2icOSP476HC9luld9YbJtI0sRVrXLIDRxTNOCFnVfQxQ1E+f+B7QcdobiqNs5TlDDThX48sh,iv:jgYNq5nAgtZv3oiRApVmm40jKo/J9Ly4M1uNgJMjIrE=,tag:WuJ+bQPwu9z4wCLWXkKsCg==,type:comment]
  postgresPassword: ENC[AES256_GCM,data:/4heBPyP8qaXts0Vk3WHZ278dHlReTuGeUPe47IwVuuTnNHeNaNRG/V1Yg==,iv:TdPl8V7suFC48v+mMnlNhjB03NyTvoCxgX0RzUu/wVI=,tag:9n18l6mO/BlQ16MICWCG5w==,type:str]
  redis-password: ""
  oidcClientId: ENC[AES256_GCM,data:Q0CHDRbxM8prbQQxNj++PsLnfaZmm6DxCYDw+1pCxIdoiYSqrsK4rg==,iv:3448PirA0B/MplxsCf5QZBTFC3gn/TMwqLPeMztEli4=,tag:uRrtssjVCm9Cj5/KIjwP7Q==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:BOuA4zfxUV8jKB9WbTyjze5kxSv8llKBl8ZVTK1PUfwwBVxVKUepez351wngpdnaZZ750XNNQGK42JtplA5v3fh3k/KjU/Kp+PLlv0I0TEttKJo8cuNRc0KFSAGOfgssZr3tpC9RIhyB7P4nO95ktzR+bkR/Fl+EeQK7pCdwxKI=,iv:ObADMRWH/X5hOIP3+whhaSLaXXQ+n4faSlizeCqyxoU=,tag:P4hdhUolSzwWLaJSYL8UZw==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeTErb0pSSVl4cTVQK0xn
        TkxGSWliUTFsM3dvMVkrYkZQYVVBa1R4S3ljClFxU2M2NUx5Wmd1MVFobjUra0NE
        ZDdiVHpFUXRudzVzSVlialBSNytwdTQKLS0tIEtqOWtOam9VK1dhbjBrZW1BaW11
        d0Mzd2pQdmJQa1ZkRkpyMTJhL1FwRjQKH5gp+nc9rgkxKEdxhvkV4VZcz1cJPTax
        hDHy303WdnQzgdbnDMhjTawU10dnGKAYObfBVi3mhFr/hBMF1MRL0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T01:28:26Z"
  mac: ENC[AES256_GCM,data:PeGu4gZa0ugoXeFIwdRFuOH0pu+w8JwxALH2B/ad1mDNjUSVnVm7A/BnBhb8H3d74In+0eYzWSZQuCQieLhQUFUfMdBPRBj7lt713zvbAEbB/Q2G/fIHYUCdnDEk5RaxeWffK2qMvVWcs1LB9i71rWw+YQ0reGRsUYnE5mkoKuk=,iv:/9TFaRrOmFZ7m0eR+yaotIkLdWpM5MltOKF1pehiEU8=,tag:SU2aCoinmKEtL1KfX0E2tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
