apiVersion: v1
kind: Secret
metadata:
  name: matrix-synapse-secret
stringData:
  registrationSharedSecret: ENC[AES256_GCM,data:fHwYtspG7gMmyuGenzRkXzJA4CIwUD59726tQA47KiBU4WW9FOPEFRPn5aFKOJpZMdzQfRgm3OYyT/lQuDCGlQ==,iv:Yh6WaXFoXaUY+YVXndaqIVikyA7ecb47kdRuH1YosTg=,tag:YtfgA0Ypoudb5xebaGPNKA==,type:str]
  postgresPassword: ENC[AES256_GCM,data:rIB5nnUXqyDY/bDBv15qlC8gMp8LeqHj5De2RADcGtkvvcn2mNyp8W4q1g==,iv:h3QKch1upXHJr31MeY0wqG1W9WfQVHW7mMy/E7Hkawc=,tag:lOgl5Xc+rKJqN0FQO11/Zw==,type:str]
  oidcClientId: ENC[AES256_GCM,data:+7vjAmTaqVG8auy0CdALNnSZk6qjZk2VyRuphc2ahH6/aHxEVTOb3A==,iv:XpYLiy/YCxLAPkxtpqJlyDZ4itdndaK44M+ZzLsobvg=,tag:FS3g41DrQZWPDKDXjk8/XQ==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:sa37haChygaOJOCtlPaHlK1/Qkqa5MRgfDsZ7ux+orudelQjurpiW+CA+C+kEvZ9Uk0ZgE5Ew6GFnNWBCMQE7C8uKx2omEWKUmMr4HdwqGdFmXEj1Fox5qKQXmkj0+ilNhbQq7eKJZCthJHQxcsnOsQgvXhsK4QhlcRO3AtRCv4=,iv:V4gKHNh6c83XwzFfFIubJioZeOYrAdtjfJDYuOgGbZ0=,tag:k3+fhsdmdwVK5hWBRUtThQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTG0vbDNLZHJNRVovVE13
        YmduVlJ4SzBjOVJZYUhnMHhGRHlMYiswNm1rClJFTUpKQnh2K21TZC9OWFBMbEFV
        WGVWSEVSMXlMTzcwdjRVa215MXo0U00KLS0tIFNyOXRGaHlkMDZQdGRSdW1yVld5
        VGJVazJtcm5oOEYwdGxrcFQwM3NFZEEKHk3eOekVtovTzFm6ExHYvCRMlnTE6Mvw
        18lDtJ09F+7Yijj9foMeOI9VglzpNpI4tXIe67F5eXyAWGdIGW+0oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T01:13:38Z"
  mac: ENC[AES256_GCM,data:XFnZ0WzUUPKIEB6P1mas8GFoirRqwL4Nvgf6HadMG52pIye7zAb4NGA7YDKJu+xoPOKzhGydBFgYHDszgGnW676WvcNmBI2A88xKlaCBbfkF2+GC+GwHP9tqCchBg3RIJkygSaiaijK8baMybjVx4lY3rqGtpOu7oj2bB+5IPOQ=,iv:SeVAd7okvTrKA31Sfswd8WM2OAH1LgaTXAILhsGzNxY=,tag:ula3wRPcn2eJZ45QrcKRrw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
