---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      version: 0.36.4
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
  interval: 1h
  values:
    domain: "https://vault.${SECRET_DOMAIN}"
    signupsAllowed: false
    invitationsAllowed: true

    adminToken:
      existingSecret: vaultwarden-secret
      existingSecretKey: ADMIN_TOKEN

    sso:
      enabled: true
      authority: "https://id.${SECRET_DOMAIN}/application/o/vaultwarden/"
      scopes: "email profile openid offline_access"
      pkce: true
      signupsMatchEmail: true
      clientId:
        existingSecretKey: SSO_CLIENT_ID
      clientSecret:
        existingSecretKey: SSO_CLIENT_SECRET
      existingSecret: vaultwarden-secret

    storage:
      data:
        name: vaultwarden-data
        size: 5Gi
        class: harvester
        path: /data
        accessMode: ReadWriteOnce

    ingress:
      enabled: false

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
