apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:rDbEAxq63sulOV7TagAcdeIRKFTwcn+pv4s9ZNSm1S4K/C3q8uQicJNMH8nAwgGaQ/uUbdDu3i1hQaCpb789rQ==,iv:gNEAHGffcaVijCVx93GuHIrZofAFjgNYrscXXddUqqo=,tag:DmuQbad6kONddj9OWgnfpg==,type:str]
  SSO_CLIENT_ID: ENC[AES256_GCM,data:ROvDq+ZsuyP5zZ1stK6qbgzoE2YhTosoFimVMnh/cRX+5Q==,iv:fe9pnhv68Vvi8kx8QNjA/8zl6KAp3ypP7pBCnV4+7hU=,tag:wfFWsq/69/Kfg2W37yCJsQ==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:mrZCrARpKDFCZqZoq5rlb/k5Yonk84V3SSU6wMcDHl26NQ==,iv:kVBhuFI3THxKlsxBjl3OJ6AT3zwPDAeeNfycqW+/0Hc=,tag:SeFu9wKrDvsS3xplJBIFQw==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQS94dTdVOTVTNy8yRjVs
        NFJ3WXY4U1V4Wkt5SzA4ZWVPclNra3VodEFVCjBmQzhQYWpRTmY4NzdGM1VnNTN1
        TnRjWERzRlhCU3NHaDU2ZGY1NzRmV1UKLS0tIHZBT0dDQ3pacFZsSGNlUVNrRGlr
        SVZxbVhaYlA4bFl0RWRBTzVUdisxQWMKEYaUW+tv4FIlUkNv0GQpVLU/kZB9N/Tu
        AjBdzzxCx5pmSrMZafIy8LynD8M3fLt5yJbm9AoL5xLfm7+RCJ7qSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T14:20:19Z"
  mac: ENC[AES256_GCM,data:1Y+nGbt375QNi7oCmcxZc2/TN7tNDrBHgEt/zsxNS2WG9wiOzklmRsVw/GtTGfwjWDLK7aeeXkRPmggnuEtPn83AM0fMFt9AR6cd7/qbJIPE+g+9CJ9j52UdRf070jvRCcjnXdnXj+FYI08f921GlW3sirjRZkmI4tFivD1wHoE=,iv:9eeNdJ/ZFNdTUVcidSGOMn0GKVtKSu2DW7q1CnWAxkE=,tag:bW/9indAsJNDulaxy5W/Lg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
