apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:WWnhniyAwZomP1ZW/A8P/eGIQ9UsiqQaWISRxBUlGtaszGdk9js1lkDDz2mXeYTg/jDVLXJd48H/8v6aeIzF/A==,iv:ODTwzStJXAEKQrG+gPOb5pZW/rGSZ38SyVVy7KjwEcU=,tag:Ygz6OmXcTSZUQ8zzakheUw==,type:str]
  SSO_CLIENT_ID: ENC[AES256_GCM,data:DiDcYyzOumctt0/0hq3eNFp6eJe3/D3W8fQWjP4TVdF6o13c9qWThw==,iv:wQsj0/Pe49YmvgDduSQESeh+MZD2Mh+8E7q4k7OMg/w=,tag:pHmcEoBd5JSrABT/FxOR9w==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:J8nzOsVswk1tlYkueDsEt5RyYLUVQcG2dJNsdd5oChZNhudsGabnQFvKr466adDYK3Uz9cI/ULeog7snh/KWfqJkZsSUjNUysU7BDv61QNexX2qLc9FrEGUnhjbR+7KgUqvJDbxrYuPdEC2E8bc3Ei4B7zoBpD6GQlDLTIVTQo4=,iv:hxq/Yaiq0bMtbCiknqfkaSLMXnx5Mx0cEP/vsDbxe5I=,tag:19+FdIW6g87844AaRiaD+g==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUjVZUUp6c0dRdmJxQXdp
        bTVjaDdSSjZjM0diQTNaYnAwVldOL3B0SmlJCks2QzN4ZWV1NUhzYVBiQVEwUzkr
        SHg2TDlydkR5SitnWlE5WG9zamJMY2cKLS0tIG9HRmJEWVVFKys3ejdJK1ZBODJl
        TUk0dEplKytpczlGUFJtL2VPSGpiSVEKXbZkOvPu6uIhRfEHVIKVgGCxSXHvr6/B
        rbkbMdmsPBvHRi/hdIpl7abZpy6LaSs8OneyV535tYCs1/tVenSOtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T16:05:41Z"
  mac: ENC[AES256_GCM,data:vCwxrmSrdx5b5HxnuOpDx+nn6w7AyNsSCjALq3LXbXxUpGbzih6Xh6S86+mDIPRkp06UaBGsD8KtJdMT1W3izJ1uUC/jCaXevjxqKBHNENBk71dkxdG2uyc2XBrWD544OueLnNxe9p85xO/90nz8VrN59ctd26harSK/KsMp/yg=,iv:/u+pPJrNiXnznfAyFLqVpG29sT7c+w0Uo4mAexe8QdI=,tag:X2IfvZVy1wRcDN1DwFJtmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
