apiVersion: v1
kind: Secret
metadata:
  name: tabby-secret
stringData:
  jwt-secret: ENC[AES256_GCM,data:NC78fCd6zubR0TS0uUdSF0Mmrre+YOsIVaVSnj69IsHvVrMB,iv:J9c98vuLBIMsSxNNxczSRJRg2FB/SoYAM7KQfd43R9E=,tag:95RJjDIjIqSNZ20hYYh+fQ==,type:str]
  config.toml: ENC[AES256_GCM,data:OYaJNg8O94EdA/T5IdsaeDQ3Ned+W5tDpNT9U9QK66BBYqTG2aJHncbn6cJZ7NvV1GGcm8aMZuVUdXCYTS2dtxuCg4IGQZEZIjI2UHY55ldzDBpMkMBxL7M9xqCLx3RqWrnmdJMhyM5PSeCY19Sogit7HK+uJ+OQ9vg8paZkKSJ3BKj68idW7D3fl3+51XtTtz2asti0yybqNQEXU0gdOO3AVJ4YtGnAE+OTo44SEsE/0n9gUNXZZXXFiFEMyqVLVfq4u7zluapqxTVIAKGLUYq0jDw/M4BqsuOj18r7+lshNNWXgpFdIfitgBQ2oy3bXl1e6Lg4ybqLzEk1Yhytg6/Wu2fyDX+XaVKdYU0bQYeOeGNOuGrEqRRRNZHZPL6oQYEHWZJa39BkJEt3efzTxj/BdUrX1tDNMWdu0F0Bod1dUm+O2TAQriYrAKQ8qiFoLGfplbrrdf4WW8Ei5qv6ufBhIt/WscXSlJl+zqNlSmZGnODPElpH3XFUWYqvNYE8dr2xcM3PfciUq4SZmy7ZGjUB4w+XNmSYpBjSAPAUfnUvgx4pDCjBWsLVEYWAL6KFoTuQHcZj6EUUbaOS9bUl3WOUbonj5IhIF18lo+j2oTqQYhRh1YZKFqkOLtMQlzkyjY7dLoFTdubjUhQrIbfsHRTXXbS4F9A8DHllUgvzwuwq9mN4msY66VEbP9aOE8Fjn7QHIYEsgkFzaywj4KAGEcPjGSS9v1DevxwG6Ar0,iv:ohWEX0Gl+sCZ6vij5fZ3Hv+hYi1aAV4I1E8yistM8aE=,tag:CHMMaW7ym822eE//CaSAQg==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bUZGYmJGUXlFNnR6TCt4
        UFphQXdMWkpFeUNiSEoya1kwL3FhZ1VLWEhZClkveGFVNkdFQ3ZIUm1wSmM2U0dV
        NDRqZVBMTjNZM0FvNzJsZkhDdEdBYzgKLS0tIDQzTVZ0d2lqbm4zaHVWRTBTRmZC
        czVmMy9ja1lPQkxTdU1FMndVaUNCQTAKTWOpjxqlAB1jRiS8Or/gDOKY6Fp1Lxgg
        LmSXxfbkN66PJrKfw/A90qcx7k8YATiU8tLb4yf58ZTXmkx3y7z/ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T12:51:45Z"
  mac: ENC[AES256_GCM,data:Xn85IjdeqFg5SaSCEqOTtTXJOrrxFTY1eDCYMdhCMFD0LyypCMVh+Q5NY2NHZwlBwWH1HpC5SMYso/Tlcf14yNT8mhwelO2HXWsfW63huqvD8Pxc+ju81UoepBqZY72jZNagLWSrC127FRUOF5+fgKFZ/dL85tFeJbW64y7kK4k=,iv:GDp7CV8ZXHG3nU3GCvEmnu2cecZuhX4DPpoUJqumwOE=,tag:24Z9v9wMMZZ08BOfFT7aUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
