apiVersion: v1
kind: Secret
metadata:
  name: mattermost-authentik-secret
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:DKGJhbHYBejMEpWf8NcA0/grARNJDIZlV+GnUzuCKgwZmj5MU27pnA==,iv:iDxIoniYCTFcWQIaUqnguHLmWep4bPOXmTZdkoMKhJ8=,tag:DwaA30AWKy5Sq0+2jhfULg==,type:str]
  client-secret: ENC[AES256_GCM,data:sv93LX+2BNcALclKeKhjG7R6Pz65mbHkICftfk9MCb7n1WimqdBXGxMzSCZa79VqSHZnMDi4BrRY8ouIYYZVoHaExVPazHwRryYE0JQ4pfqH5QJUhZKiP0mK4Re/phPQE86pE0sxPleWyW5o660AGGK97TFpsy7LVO74XZDxEk4=,iv:kZqhqkPIflXX8wcKxKCGQqZVIuVCLDjBk0UU/643xzg=,tag:IDl5FMcC/eU215J3Y3ioNA==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdUNiNldvSzcvZEFrYmlV
        V0REc3JEVHZGdDFKMEVObXNNU2FsOHlBMmxVCmtOWlBJcWNTL3ordjFVcnBiVVVy
        dlRLSTdOK2R2aHFTbng4aHltaHlWTUkKLS0tIHNjSWNyazEzYXpKSVFPMHF5aWJp
        NjdmRnRMeVNXQU9UWEdRMisrT3NTSDgKZ2bKFOU92ECUlpF4nNMbUcCnJ0dirYZN
        KtExt2+lq7s6OvR6Kxn6DQe6NagMST7CvOrUz4KgFzbzs75MN11gZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T17:19:47Z"
  mac: ENC[AES256_GCM,data:plPLOevLNr655B9TZoAZOkSBLjCvQJpRpIzUHnkhbc2l6OaW/ZuP0AD7b8ADyNbMkxEzIXlHvw8Qg8LPRJg3HsO4mmj2oI+y/ycx39aUYBBoos13MZi8e793sPfpnrggPxuuNZafh7G6uQjnsKV99DK1+jfa59RZe0tkXKJ+cMI=,iv:hv+lQrxAgGmEEhSM/3aggIqI+CprSFMNaZRJodwNbR4=,tag:Gei7Wd9zluwYqTQb+8mNLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
