apiVersion: v1
kind: Secret
metadata:
  name: mattermost-pg-secret
stringData:
  SECRET_MATTERMOST_PG_PASSWORD: ENC[AES256_GCM,data:h79BwBP3VOED3f+fI9svKI7rv3Buv6qVMPIFUBV+vU4=,iv:ipLYzJNAh4QGyA5ht6ImcWDeowG1W1K0gCuBMcSClxw=,tag:r9DlVzeDOlJHyrCpIQ4+MQ==,type:str]
sops:
  age:
    - recipient: age16axld0tr7u7rhkm0dfcj0elmw8lzqxsm8rykrdafrrk5dxt3g5equwm578
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITURuLzBLT1ZFTFVWKzNi
        ejNtY3ZqTmNxU1JwUFdweUtWNm1GNHV6bm5JCjd0aTFGQkE3ZXpEcmRnRVBoQUVv
        eFVSUUJUb1dCYm1nM3JaZmh3Z1NFcGcKLS0tIGgyY1AwNVU4UTI4SXdPeUIyT0xj
        VVI4YktvRzYyWkZLNzAyTGlBS2VlcUkKIIjU5tmWSLgJGZDkY4DNcRB1qCJqTZAx
        yXHnxVFgarKDa+ElzK/L3IPOB8rqwc1nT6r/AmGShl1O3aDKqZxzmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T17:40:49Z"
  mac: ENC[AES256_GCM,data:EpWmvpInuBvlCqyUnCRxhIWL10h0NFjs5wZsJJco/7oTk244kJ2gtsqU0maN5FNf0KvVTkEl5Inz/QqM4mbJSTL9DVsJmFmsmIGkGdOrIerg8rb+SKudDrTvKuFblFn2ZfH2IZSTcQ62ewxBisGpVcaVgQG2lmAe/OgSy4REwLY=,iv:uO2FqdvG62KNJMODzB317fVNr5ioZfpam6ocSkSYZy4=,tag:L21qnOoavZuf8iHm/eBe4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
