---
apiVersion: v1
kind: Service
metadata:
  name: navidrome-tailscale
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "navidrome"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/controller: navidrome
    app.kubernetes.io/instance: navidrome
    app.kubernetes.io/name: navidrome
  ports:
    - name: http
      port: 4533
      targetPort: 4533
      protocol: TCP
